sonar.projectKey=mnv-autos-clientes-ng
sonar.projectName=mnv-autos-clientes-ng
sonar.projectVersion=1.0.0-SNAPSHOT
sonar.sourceEncoding=UTF-8
sonar.sources=apps
sonar.exclusions=**/node_modules/**,**/*.spec.ts,./decorate-angular-cli.js,./jest.config.js,**/tools/**,./apps/mvp-assessagrariospoc-ng/api/**,./apps/mvp-assessagrariospoc-ng-e2e/**
sonar.tests=apps
sonar.test.inclusions=**/*.spec.ts
sonar.ts.tslintconfigpath=tslint.json
sonar.javascript.lcov.reportPaths=coverage/apps/mnv-autos-clientes-ng/lcov.info
